_target_: src.models.manifold_mixup.TextClassificationTransformerWrapperMixup

optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 2e-5
  eps: 1e-8

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau

monitor:
  metric_to_track: 'val_loss'

pretrained_model_name_or_path: "distilbert-base-uncased"
