_target_: src.models.mixup_module.MixUpModule
alpha: 1.0

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 3072
  lin1_size: 1536
  lin2_size: 768
  lin3_size: 384
  output_size: 10

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0005

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau

monitor:
  metric_to_track: 'val/acc'