_target_: src.models.base_module.BaseModule

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 256
  lin2_size: 256
  lin3_size: 256
  output_size: 10

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 0.001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau

monitor:
  metric_to_track: 'val/acc'

