_target_: src.models.base_module.BaseModule
lr: 0.1
weight_decay: 0.0001

net:
  _target_: torchvision.models.resnet18

# ref for hp: https://github.com/facebookresearch/mixup-cifar10/blob/main/train.py