defaults:
  - default.yaml

model_checkpoint:
  monitor: "val_accuracy"

early_stopping:
  monitor: "val_accuracy"

track_gradients:
  _target_: src.callbacks.default.TrackCleanGradientsTransformer
  
generate_EH:
  _target_: src.callbacks.default.GenerateEH_transformer