defaults:
  - default.yaml

model_checkpoint:
  monitor: "val_accuracy" # name of the logged metric which determines when model is improving

early_stopping:
  monitor: "val_accuracy" # name of the logged metric which determines when model is improving

track_gradients:
  _target_: src.callbacks.default.TrackCleanGradientsTransformer