_target_: src.datamodules.cifar10c_datamodule.CIFAR10CDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 128
val_test_split: [5_000, 5_000]
num_workers: 0
pin_memory: False